blank_issues_enabled: false
contact_links:
  - name: Terraform Language or Workflow Feedback and Questions
    url: https://github.com/hashicorp/terraform/issues/new/choose
    about: Terraform Core has its own repository, any language (HCL) or workflow related issues or questions should be directed there.
  - name: terraform-plugin-go Feedback
    url: https://github.com/hashicorp/terraform-plugin-go/issues/new/choose
    about: terraform-plugin-go has its own repository, any feedback related to it should be directed there.
  - name: ❓ Provider Development Questions
    url: https://discuss.hashicorp.com/c/terraform-providers/tf-plugin-sdk
    about: Please ask and answer questions about provider development through the Plugin SDK Community Forum.
