# Continuous integration handling for GoReleaser
name: ci-goreleaser

on:
  pull_request:
    paths:
      - .goreleaser.yml

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: go-version
        # Reference: https://github.com/actions/setup-go/issues/23
        run: echo "version=$(cat ./.go-version)" >> "$GITHUB_OUTPUT"
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ steps.go-version.outputs.version }}
      - uses: goreleaser/goreleaser-action@v3
        with:
          args: check
